version: "3"

services:
  db:
    image: mysql:8.0.21
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: go_project
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  cache:
    image: redis:6.0.9-alpine
    ports:
      - "6380:6379"

  cassandra:
    image: bitnami/cassandra:latest